version: '3'
services:
  wordpress:
    container_name: wordpress
    image: foohyfooh/jkn_solutions
    ports:
      - "80:80"
      - "443:443"
    restart: always
    environment:
      WORDPRESS_DB_HOST: PLACEHOLDER_DB_HOST:PLACEHOLDER_DB_PORT
      WORDPRESS_DB_USER: PLACHOLDER_DB_USER
      WORDPRESS_DB_PASSWORD: PLACEHOLDER_DB_PASS
    working_dir: /var/www/html
